import Head from 'next/head'
import localFont from '@next/font/local'
import Footer from './Footer'
import NavBar from './NavBar'

interface LayoutProps {
  children: React.ReactNode
  title: string
}

const font = localFont({
  src: '../../../public/fonts/MaisonNeue-Thin.otf',
  weight: '200',
})

const Layout = ({ children, title }: LayoutProps) => {
  return (
    <div className={`layout ${font.className} `}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>{children}</main>
      <Footer />
    </div>
  )
}

export default Layout
