import Head from 'next/head'

import NavBar from './NavBar'

interface LayoutProps {
  children: React.ReactNode
  title: string
}

const Layout = ({ children, title }: LayoutProps) => {
  return (
    <div className="layout">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.cdnfonts.com/css/maison-neue"
          rel="stylesheet"
        />
      </Head>
      <NavBar />
      <main>{children}</main>
    </div>
  )
}

export default Layout
